name: gitlab
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:19.0.1-ce.0
    restart: always
    env_file: .env
    hostname: ${HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # External url. HTTP -> 80. HTTPS -> 433
        external_url 'https://${HOSTNAME}'
        # Container registry
        gitlab_rails['registry_enabled'] = true
        # External url. HTTP -> 80. HTTPS -> 433
        registry_external_url 'https://${REGISTRY_HOSTNAME}'
        # SMTP
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_SERVER}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = "none"
        gitlab_rails['gitlab_email_from'] = '${SMTP_DEFAULT_FROM_EMAIL}'
        gitlab_rails['gitlab_email_reply_to'] = '${SMTP_DEFAULT_FROM_EMAIL}'
        # Deshabilito el WEB IDE y marketplace de extensiones
        gitlab_rails['web_ide_clientside_preview_enabled'] = false
        gitlab_rails['vscode_extension_marketplace_enabled'] = false
        # Puma workers (reemplaza Unicorn desde GitLab 13+)
        puma['worker_processes'] = 2
        puma['min_threads'] = 1
        puma['max_threads'] = 4
        # Sidekiq
        sidekiq['concurrency'] = 5
        # PostgreSQL
        postgresql['shared_buffers'] = "256MB"
        postgresql['max_connections'] = 100
        postgresql['work_mem'] = "8MB"
        # Redis 
        redis['maxmemory'] = "200mb"
        redis['maxmemory_policy'] = "allkeys-lru"
        # Prometheus y monitoreo interno 
        # Deshabilitalo si no usás el monitoreo interno de GitLab
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        gitlab_exporter['enable'] = false

        # Gitaly (ajuste de workers)
        gitaly['configuration'] = {
          concurrency: [
            { 'rpc' => "/gitaly.SmartHTTPService/PostReceivePack", 'max_per_repo' => 3 },
            { 'rpc' => "/gitaly.SSHService/SSHUploadPack", 'max_per_repo' => 3 },
          ]
        }
    ports:
      #- ${APP_PORT}:80
      - ${APP_PORT}:443
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - ./certs/registry.desarrollosur.com.ar.crt:/etc/gitlab/ssl/registry.desarrollosur.com.ar.crt
      - ./certs/registry.desarrollosur.com.ar.key:/etc/gitlab/ssl/registry.desarrollosur.com.ar.key
        #logging:
        #driver: none
